[tool.poetry]
name = "my_hackathon_bot"
version = "0.1.0"
description = ""
authors = ["WebDev22"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyTelegramBotAPI = "4.10.0"
requests= "^2.28.22"
lyricsgenius = "^3.0.1"
<<<<<<< Updated upstream
=======
pymongo = "^4.3.3"

>>>>>>> Stashed changes
[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
